### ISSUE TITLE
How to modify code to only apply to custom class

### ISSUE THREAD

**Issue by lvzhenbo** [lowlighter/matcha#51]
I'm working on a feature to convert markdown to html, and since it's generally unstyled, I'd like to replace it with some off-the-shelf styles, but I don't want to affect the overall styling, so how do I do it?

**Comment by lowlighter** [comment]
Since matcha is a semantic library, I think the only way to do what you want would be to use [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM#declaratively_with_html) to embed the markdown sections. 

Shadow roots are somewhat isolated from the rest of the document so you can include matcha in them and it wouldn't conflict with the overall styling.

Something along:
![image](https://github.com/user-attachments/assets/82013103-131f-4f43-83ac-7a80a52f9879)
<details>

<summary>See code</summary>

```html
<html>
    <head>
        <style>
            body { background: whitesmoke; }
            [data-shadow] { border-radius: 5px; padding: 1rem; }    
        </style>
    </head>
    <body>
        <h1>Global DOM</h1>
        <p>This section keeps the defaults styling.</p>
        <div data-shadow>
            <template shadowrootmode="open">
                <h1>Shadow DOM</h1>
                <p>This section is isolated form the rest of the document.</p>
                <pre><code><span class="hljs-keyword">const</span> foo = <span class="hljs-string">"bar"</span></pre></code>
                <style>@import "https://matcha.mizu.sh/matcha.css"</style>
            </template>
        </div>
    <body>
</html>
```

</details>

- Snippet render: https://real-wasp-90.deno.dev/
- Snippet playground: https://dash.deno.com/playground/real-wasp-90
- Matcha doc: https://matcha.mizu.sh/#shadow-root

**Comment by lvzhenbo** [comment]
Thanks a lot for the answer, but I'm using vue to build the program instead of native js, and using shadow DOM would be cumbersome, so I've given the conundrum to copilot edit, which wraps the styles in a custom class and solves the problem for now.
